@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.hrznstudio.spatial.client.vanillawrappers;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;